# Agent names

names = {"dqn": "DQN",
         "ddqn": "DDQN",
         "dddqn": "DDDQN",
         "dpg": "DPG",
         "ddpg": "DDPG",
         "a2c_discrete": "A2C_discrete",
         "a2c_continuous": "A2C_continuous",
         "a2c_discrete_queue": "A2C_discrete_queue",
         "a2c_continuous_queue": "A2C_continuous_queue",
         "a3c_discrete": "A3C_discrete",
         "a3c_continuous": "A3C_continuous",
         "ppo_discrete": "PPO_discrete",
         "ppo_continuous": "PPO_continuous",
         "ppo_discrete_parallel": "PPO_discrete_async",
         "ppo_continuous_parallel": "PPO_continuous_async",
         "pposqp_continuous_parallel": "PPOSQP_continuous_parallel",
         "ppooptcicles_continuous_parallel": "PPOOPTCICLES_continuous_parallel",
         "ppo_continuous_parallel_hindsight": "ppo_continuous_parallel_hindsight",
         "ppooptcicles_continuous_parallel_v2": "ppooptcicles_continuous_parallel_v2"}